# helm-charts/values.template.yaml
replicaCount: 1

# Docker image settings
image:
  repository: "thirdaiplatform.azurecr.io/thirdai_platform_release-test-main"
  tag: "v1.1.6"
  pullPolicy: IfNotPresent

# Docker credentials secret
dockerCredentialsSecret: "docker-credentials-secret"

service:
  port: 80
  type: ClusterIP

# Ingress settings (Nginx). Route /api to modelbazaar
ingress:
  className: "nginx"
  hostname: "a41f26420941f4174a1d62876e22477e-1275523647.us-west-1.elb.amazonaws.com" # Will be set automatically (or prompted) when TLS is enabled.
  path: "/api"
  tlsSecret: thirdai-platform-tls
  use_tls: true # "true" or "false"

# EFS CSI Persistent Volume Claim settings
efs:
  storageClassName: efs-sc
  size: "5Gi"
  fileSystemId: "fs-045cfbaf5d3195982"

modelbazaar_resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

# License file secret reference
licenseSecretName: "thirdai-platform-license"

keycloak:
  image: "thirdaiplatform.azurecr.io/keycloak:26.0.0"
  db: "postgres"
  dbUrl: "jdbc:postgresql://thirdai-eks-rds-8da2bp.c3woa2m66ufq.us-west-1.rds.amazonaws.com:5432/modelbazaar"
  dbUsername: "myadmin"
  dbPassword: "mypassword"
  serviceType: ClusterIP

# Example environment variables
env:
  PUBLIC_MODEL_BAZAAR_ENDPOINT: "http://example.com/"
  LICENSE_PATH: "/model_bazaar/license/ndb_enterprise_license.json"
  PRIVATE_MODEL_BAZAAR_ENDPOINT: "http://example.com/"
  NOMAD_ENDPOINT: "http://172.17.0.1:4646/"
  SHARE_DIR: "/model_bazaar"
  JWT_SECRET: "my-jwt-secret"
  ADMIN_USERNAME: "admin"
  ADMIN_MAIL: "admin@thirdai.com"
  ADMIN_PASSWORD: "password"
  AUTOSCALING_ENABLED: "false"
  AUTOSCALER_MAX_COUNT: "10"
  GENAI_KEY: ""
  IDENTITY_PROVIDER: "postgres"
  KEYCLOAK_SERVER_URL: "https://my-keycloak.example.com"
  USE_SSL_IN_LOGIN: "true"
  DATABASE_URI: "postgresql://myadmin:mypassword@thirdai-eks-rds-8da2bp.c3woa2m66ufq.us-west-1.rds.amazonaws.com:5432/modelbazaar"
