replicaCount: 1

# Docker image settings
image:
  repository: "thirdaiplatform.azurecr.io/thirdai_platform_release-test-main"
  tag: "v1.1.6"
  pullPolicy: IfNotPresent

# The name of the Docker credentials secret that you created with kubectl create secret ...
dockerCredentialsSecret: "docker-credentials-secret"

service:
  port: 80
  type: ClusterIP

# Ingress settings (Nginx). Route /api to modelbazaar
ingress:
  enabled: true
  className: "nginx"
  hostname: "ae5d3eb02294244d9a82f06eb1e3bdce-2112299573.us-west-1.elb.amazonaws.com"
  path: "/api"
  tlsSecret: thirdai-platform-tls
  use_tls: true

# EFS CSI Persistent Volume Claim settings
efs:
  storageClassName: "efs-sc"
  size: 1Gi

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

# License file secret reference
licenseSecretName: "thirdai-platform-license"

keycloak:
  image: "thirdaiplatform.azurecr.io/keycloak:26.0.0"
  hostname: "my-keycloak.example.com"
  db: "postgres"
  dbUrl: "jdbc:postgresql://database-2.c3woa2m66ufq.us-west-1.rds.amazonaws.com:5432/postgres"
  dbUsername: "postgres"
  dbPassword: "demo_machine"
  serviceType: ClusterIP

# Example environment variables
env:
  PUBLIC_MODEL_BAZAAR_ENDPOINT: "http://thirdaiplatform.com/"
  LICENSE_PATH: "/model_bazaar/license/ndb_enterprise_license.json"
  PRIVATE_MODEL_BAZAAR_ENDPOINT: "http://thirdaiplatform.com/"
  NOMAD_ENDPOINT: "http://172.17.0.1:4646/"
  SHARE_DIR: "/model_bazaar"
  JWT_SECRET: "my-jwt-secret"
  ADMIN_USERNAME: "admin"
  ADMIN_MAIL: "admin@thirdai.com"
  ADMIN_PASSWORD: "password"
  AUTOSCALING_ENABLED: "false"
  AUTOSCALER_MAX_COUNT: "10"
  GENAI_KEY: ""
  IDENTITY_PROVIDER: "my-idp"
  KEYCLOAK_SERVER_URL: "https://my-keycloak.example.com"
  USE_SSL_IN_LOGIN: "true"
  DATABASE_URI: "postgresql://postgres:demo_machine@database-2.c3woa2m66ufq.us-west-1.rds.amazonaws.com:5432/postgres"
