# helm-charts/values.template.yaml
replicaCount: 1

# Docker image settings
image:
  repository: "thirdaiplatform.azurecr.io/thirdai_platform_eks-test"
  tag: "v0.0.13"
  pullPolicy: IfNotPresent

# Docker credentials secret
dockerCredentialsSecret: "docker-credentials-secret"

service:
  port: 80
  type: ClusterIP

# Ingress settings (Nginx). Route /api to modelbazaar
ingress:
  className: "nginx"
  hostname: "${INGRESS_HOSTNAME}" # Will be set automatically (or prompted) when TLS is enabled.
  path: "/api"
  tlsSecret: thirdai-platform-tls

# EFS CSI Persistent Volume Claim settings
efs:
  storageClassName: efs-sc
  size: "5Gi"
  fileSystemId: "${EFS_FILE_SYSTEM_ID}"

modelbazaar_resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

# License file secret reference
licenseSecretName: "thirdai-platform-license"

keycloak:
  image: "thirdaiplatform.azurecr.io/keycloak:26.0.0"
  db: "postgres"
  dbUrl: "jdbc:${KEYCLOAK_DB_URL}"
  dbUsername: "${KEYCLOAK_DB_USERNAME}"
  dbPassword: "${KEYCLOAK_DB_PASSWORD}"
  serviceType: ClusterIP

# Example environment variables
env:
  KUBERNETES: "true"
  SHARE_DIR: "/model_bazaar"
  JWT_SECRET: "my-jwt-secret"
  ADMIN_USERNAME: "admin"
  ADMIN_MAIL: "admin@thirdai.com"
  ADMIN_PASSWORD: "password"
  IDENTITY_PROVIDER: "postgres"
  DATABASE_URI: "postgresql://postgres:4yChWUTjZ22x@test-eks.cjhmqzlwgr5q.us-east-1.rds.amazonaws.com:5432/postgres"
  GRAFANA_DB_URL: "postgresql://postgres:4yChWUTjZ22x@test-eks.cjhmqzlwgr5q.us-east-1.rds.amazonaws.com:5432/grafana"
  LICENSE_PATH: "/model_bazaar/license/ndb_enterprise_license.json"
