# helm-charts/values.template.yaml
replicaCount: 1

# Docker image settings
image:
  repository: "thirdaiplatform.azurecr.io/thirdai_platform_eks-test"
  tag: "v0.0.54"
  pullPolicy: IfNotPresent

# Docker credentials secret
dockerCredentialsSecret: "docker-credentials-secret"

service:
  port: 80
  type: ClusterIP

# Ingress settings (Nginx). Route /api to modelbazaar
ingress:
  className: "nginx"
  hostname: "${INGRESS_HOSTNAME}"
  path: "/api/v2"
  tlsSecret: thirdai-platform-tls

# EFS CSI Persistent Volume Claim settings
efs:
  fileSystemId: "${EFS_FILE_SYSTEM_ID}"
  shareDir: "/thirdai_platform/v1"

modelbazaar_resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

# License file secret reference
licenseSecretName: "thirdai-platform-license"

keycloak:
  image: "thirdaiplatform.azurecr.io/keycloak:26.0.0"
  db: "postgres"
  dbUrl: "jdbc:${KEYCLOAK_DB_URL}"
  dbUsername: "${KEYCLOAK_DB_USERNAME}"
  dbPassword: "${KEYCLOAK_DB_PASSWORD}"
  serviceType: ClusterIP

# Example environment variables
env:
  INGRESS_HOSTNAME: "${INGRESS_HOSTNAME}"
  PRIVATE_MODEL_BAZAAR_ENDPOINT: "http://thirdai-internal-ingress-nginx-controller.thirdai-platform.svc.cluster.local/"
  KUBERNETES: "true"
  SHARE_DIR: "/model_bazaar"
  JWT_SECRET: "my-jwt-secret"
  ADMIN_USERNAME: "admin"
  ADMIN_MAIL: "admin@thirdai.com"
  ADMIN_PASSWORD: "password"
  IDENTITY_PROVIDER: "postgres"
  DATABASE_URI: "${MODELBAZAAR_DB_URI}"
  GRAFANA_DB_URL: "${GRAFANA_DB_URL}"
  LICENSE_PATH: "/model_bazaar/license/ndb_enterprise_license.json"
