{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ner-backend.fullname" . }}-proxy
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: {{ .Values.api.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "ner-backend.fullname" . }}-api
                port:
                  name: backend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ner-backend.fullname" . }}-api
                port:
                  name: frontend
{{- end }}

