# templates/pvc.yaml
{{- if .Values.rabbitmq.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ner-backend.fullname" . }}-rabbitmq
spec:
  accessModes:
    - {{ .Values.rabbitmq.persistence.accessMode }}
  storageClassName: {{ .Values.rabbitmq.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.rabbitmq.persistence.size }}
{{- end }}
