---
- name: Copy airgapped license file if it exists
  when:
    - airgapped_license_path is defined
    - airgapped_license_path | length > 0
    - ansible_host_private_ip == critical_services_nodes[0].private_ip
  block:
    - name: Copy the airgapped license file
      ansible.builtin.copy:
        src: "{{ airgapped_license_path }}"
        dest: "{{ shared_file_system.shared_dir }}/license/"
        owner: "{{ critical_services_nodes[0].ssh_username }}"
        group: nomad_nfs
        mode: "0664"
      register: result

    - name: Fail if airgapped license file copy failed
      ansible.builtin.fail:
        msg: "Failed to copy the airgapped license file to {{ shared_file_system.shared_dir }}/license/ on {{ ansible_host }}. Error: {{ result }}"
      when: result is failed

  rescue:
    - name: Rollback - Remove copied airgapped license file on failure
      ansible.builtin.find:
        paths: "{{ shared_file_system.shared_dir }}/license/"
        patterns: "{{ airgapped_license_path | basename }}"
      register: find_result

    - name: Remove found airgapped license file
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      when: find_result.matched > 0
      loop: "{{ find_result.files }}"
      ignore_errors: true

    - name: Fail playbook with error
      ansible.builtin.fail:
        msg: "Airgapped license file copy failed and rollback performed on {{ ansible_host }}."
