apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelbazaar-discovery
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: thirdai-platform
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - "nodes/metrics"
  - "nodes/stats"
  - "nodes/proxy"
  verbs:
  - get
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get