apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thirdai-platform-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: modelbazaar
                port:
                  number: {{ .Values.service.port }}
          - path: /keycloak
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8180
          - path: /keycloak/health
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 9000
