apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: {{ .Values.keycloak.serviceType }}
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8180
      targetPort: http
    - name: health
      port: 9000
      targetPort: health
    - name: jgroups
      port: 7800
      targetPort: jgroups
