apiVersion: v1
kind: PersistentVolume
metadata:
  name: thirdai-platform-share-dir-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "{{ .Values.efs.fileSystemId }}::{{ .Values.efs.shareDir }}"
