apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thirdai-platform-shared-dir-pvc
spec:
  volumeName: efs-shared-dir-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
