apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-bazaar-pvc
spec:
  volumeName: thirdai-platform-share-dir-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
