apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: modelbazaar
spec:
  ingressClassName: "nginx"
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: modelbazaar
                port:
                  number: {{ .Values.service.port }}
