---
- name: Install libraries required for aws secret lookup on Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-boto3
    - python3-botocore
  when: ansible_pkg_mgr == "apt"
  register: result_apt
  failed_when: result_apt is failed

- name: Install libraries required for aws secret lookup on Amazon-linux 3
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3-boto3
    - python3-botocore
  when: ansible_pkg_mgr == "dnf"
  register: result_dnf
  failed_when: result_dnf is failed

- name: Retrieve Secrets from aws secret manager
  ansible.builtin.set_fact:
    secrets: "{{ lookup('amazon.aws.aws_secret', aws_secret_name) }}"